### ISSUE TITLE
signup

### ISSUE THREAD

**Issue by Hwilliams8548** [cheeserox/pokTwo#5]
add a fucking captcha or something, i made like 8k accounts in 30 minutes with 13 lines of code.

**Comment by PF94** [comment]
hcaptchas are kind of shit and i'm not willing to let google be able to track poktwo's register page.

me and john have already conceptualized another solution, that being invite keys.

also you're a fucking retard for doing that and caused the site to go down all because you're mad at me for removing you access from some 2014 brand account LOL

**Comment by Hwilliams8548** [comment]
@PF94 invite keys? thats your best option? You could make your own simple captcha. For example, a math one. Invite keys just stop new users from joining.

**Comment by Hwilliams8548** [comment]
"also you're a fucking retard for doing that and caused the site to go down"
what do you think i wanted?

**Comment by PF94** [comment]
> Invite keys just stop new users from joining.

with uTue's community essentially being the reason as to why SuxCox (which was the inspiration of pokTwo) just shutdown, i'd prefer closing up pokTwo to only a few select OYC people.

**Comment by Hwilliams8548** [comment]
i can see your edits without reloading the page, thats cool

**Comment by Hwilliams8548** [comment]
also when is the site coming back? sometimes i like to use a vpn and just see whats on there..

**Comment by PF94** [comment]
> "also you're a fucking retard for doing that and caused the site to go down" what do you think i wanted?

To point out that the site doesn't have protection against spamming... which makes sense.

You weren't the first person to spam my sites. squareBracket was attacked the exact same way near the end of July 2021.

https://www.youtube.com/watch?v=AwP937z27F4

![image](https://user-images.githubusercontent.com/45898787/166132446-55b2981f-3cc3-42f2-9770-d6e740980ea0.png)

15k total users.

**Comment by Hwilliams8548** [comment]
they most likely just spammed numbers and stuff, i spammed a whole list of scraped vidlii accounts

**Comment by PF94** [comment]
> they most likely just spammed numbers and stuff, i spammed a whole list of scraped vidlii accounts

speaking of VidLii, I'm pretty sure someone in there was behind the squareBracket spamming, as there was a reference to a neo-nazi guy in one of the usernames they spammed.

**Comment by Hwilliams8548** [comment]
Your spammers actually had usernames that meant something? over here we have mquin40440, mquin40441, mquin40442, mquin40443, mquin40444, etc

**Comment by PF94** [comment]
![image](https://user-images.githubusercontent.com/45898787/166132528-b4a8e50a-3bb4-4b1a-9e2c-40a39fdf4ff2.png)

**Comment by Hwilliams8548** [comment]
what

**Comment by Hwilliams8548** [comment]
> Your spammers actually had usernames that meant something? over here we have mquin40440, mquin40441, mquin40442, mquin40443, mquin40444, etc
> 
> (on betatube)

oh and also once it got passed mquin40449 it went to mquin404410 LMFAO
